### ISSUE TITLE
time seems invalid in influxdb

### ISSUE THREAD

**Issue by vincentserpoul** [Abramovic/logrus_influxdb#1]
Hi,

First of all, thanks for the module, good job :+1: .
But I have an issue I'm not sure why.
It actually writes to the influxdb but the time in influxdb indicates 1970, like it was close to timestamp 0.
Have you seen that behaviour before?

**Comment by abramovic** [comment]
That's a great catch, thanks! 

What's happening is we're letting InfluxDB create the timestamp instead of using the one from Logrus. 

Resolved: https://github.com/Abramovic/logrus_influxdb/issues/2

**Comment by abramovic** [comment]
Please let me know if this fixes things for you :)

**Comment by vincentserpoul** [comment]
I actually still see 1970-01-01T00:00:01.446548954Z, I will dig into it and continue contributing to the repo.

**Comment by vincentserpoul** [comment]
I actually removed Precision and it now works.
My influxdb version is v0.9.3, I compiled it from scratch with their dockerfiles and shell scripts.

I hope it doesn't create any issue on your side and that we can merge the PR https://github.com/Abramovic/logrus_influxdb/pull/3

**Comment by vincentserpoul** [comment]
bump

**Comment by abramovic** [comment]
Merged :)

**Comment by vincentserpoul** [comment]
:+1:
